/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SecondRouteRouteImport } from './routes/second-route'
import { Route as IndexRouteImport } from './routes/index'

const SecondRouteRoute = SecondRouteRouteImport.update({
  id: '/second-route',
  path: '/second-route',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/second-route': typeof SecondRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/second-route': typeof SecondRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/second-route': typeof SecondRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/second-route'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/second-route'
  id: '__root__' | '/' | '/second-route'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SecondRouteRoute: typeof SecondRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/second-route': {
      id: '/second-route'
      path: '/second-route'
      fullPath: '/second-route'
      preLoaderRoute: typeof SecondRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SecondRouteRoute: SecondRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
